server:
  port: 9999
  servlet:
    context-path: /idlecherry

#spring template
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/idlecherry?characterEncoding=UTF-8
    username: root
    password: Zz1234zz

#mybatis
mybatis:
  mapper-locations: classpath:com/sydney/mapper/*.xml
  type-aliases-package: com.sydney.entity

#log
logging:
  level:
    root: info
    com.sydney: debug